apiVersion: apps/v1
kind: Deployment
metadata:
  name: jekyll-blog
  labels:
    app: jekyll-blog
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jekyll-blog
  template:
    metadata:
      labels:
        app: jekyll-blog
    spec:
      containers:
      - name: jekyll-blog
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: blog-content
          mountPath: /usr/share/nginx/html
      volumes:
      - name: blog-content
        configMap:
          name: blog-content
---
apiVersion: v1
kind: Service
metadata:
  name: jekyll-blog-service
spec:
  selector:
    app: jekyll-blog
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jekyll-blog-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: blog.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: jekyll-blog-service
            port:
              number: 80